import { useEffect, useState } from 'react';
import { Boxes, LoaderCircle, Plus, RefreshCw, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { usePos } from '../context/PosContext.tsx';

type StockItem = { id: number; name: string; sku: string | null; unit: string; onHandMilliunits: number; reorderLevelMilliunits: number };
type Movement = { id: number; inventoryItemId: number; deltaMilliunits: number; movementType: string; reason: string; createdAt: string };

const units = ['each', 'g', 'kg', 'ml', 'l'];
const displayQuantity = (value: number) => (value / 1000).toLocaleString(undefined, { maximumFractionDigits: 3 });

export default function InventoryView() {
  const { menuItems, showToast } = usePos();
  const [items, setItems] = useState<StockItem[]>([]); const [movements, setMovements] = useState<Movement[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(''); const [sku, setSku] = useState(''); const [unit, setUnit] = useState('each'); const [opening, setOpening] = useState('0'); const [reorder, setReorder] = useState('0');
  const [adjustId, setAdjustId] = useState<number | null>(null); const [adjustment, setAdjustment] = useState(''); const [movementType, setMovementType] = useState('receipt'); const [reason, setReason] = useState('');
  const [recipeMenuId, setRecipeMenuId] = useState<number | null>(menuItems[0]?.id || null); const [recipeRows, setRecipeRows] = useState<Array<{ inventoryItemId: number; quantity: string }>>([]);
  const load = async () => { setLoading(true); try { const response = await fetch('/api/inventory'); const body = await response.json(); if (!response.ok) throw new Error(body.error); setItems(body.items); setMovements(body.movements); } catch (error: any) { showToast(error.message || 'Unable to load inventory'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { const response = await fetch('/api/inventory', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, sku, unit, onHandMilliunits: Math.round(Number(opening) * 1000), reorderLevelMilliunits: Math.round(Number(reorder) * 1000) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setName(''); setSku(''); setOpening('0'); setReorder('0'); await load(); showToast('Inventory item created'); } catch (error: any) { showToast(error.message); } finally { setBusy(false); } };
  const adjust = async (event: React.FormEvent) => { event.preventDefault(); if (!adjustId) return; setBusy(true); try { const factor = movementType === 'waste' ? -1 : 1; const response = await fetch(`/api/inventory/${adjustId}/adjustments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ deltaMilliunits: Math.round(Math.abs(Number(adjustment)) * 1000) * factor, movementType, reason }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setAdjustId(null); setAdjustment(''); setReason(''); await load(); showToast('Stock movement recorded'); } catch (error: any) { showToast(error.message); } finally { setBusy(false); } };
  const saveRecipe = async () => { if (!recipeMenuId) return; setBusy(true); try { const ingredients = recipeRows.filter(row => row.inventoryItemId && Number(row.quantity) > 0).map(row => ({ inventoryItemId: row.inventoryItemId, quantityMilliunits: Math.round(Number(row.quantity) * 1000) })); const response = await fetch(`/api/menu-items/${recipeMenuId}/recipe`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ingredients }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); showToast('Menu recipe saved'); } catch (error: any) { showToast(error.message); } finally { setBusy(false); } };
  if (loading) return <div className="grid flex-1 place-items-center"><LoaderCircle className="size-7 animate-spin text-indigo-600" /></div>;
  return <div className="flex-1 overflow-y-auto bg-slate-50 p-4 lg:p-6"><div className="mx-auto max-w-6xl space-y-6"><header className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Boxes className="text-indigo-600" /><h1 className="text-xl font-bold">Inventory & recipes</h1></div><p className="mt-1 text-sm text-slate-500">Location stock, traceable movements, reorder levels, and automatic recipe depletion.</p></div><Button variant="outline" onClick={load}><RefreshCw />Refresh</Button></header>
    <form onSubmit={create} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-6"><div className="md:col-span-2"><Label>Name</Label><Input required value={name} onChange={e => setName(e.target.value)} /></div><div><Label>SKU</Label><Input value={sku} onChange={e => setSku(e.target.value)} /></div><div><Label>Unit</Label><select value={unit} onChange={e => setUnit(e.target.value)} className="mt-1 h-9 w-full rounded-md border px-3 text-sm">{units.map(value => <option key={value}>{value}</option>)}</select></div><div><Label>Opening quantity</Label><Input type="number" min="0" step="0.001" value={opening} onChange={e => setOpening(e.target.value)} /></div><div><Label>Reorder at</Label><Input type="number" min="0" step="0.001" value={reorder} onChange={e => setReorder(e.target.value)} /></div><Button className="md:col-start-6" disabled={busy}><Plus />Add item</Button></form>
    <section className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Item</th><th className="p-3">On hand</th><th className="p-3">Reorder level</th><th className="p-3"></th></tr></thead><tbody className="divide-y">{items.map(item => <tr key={item.id} className={item.onHandMilliunits <= item.reorderLevelMilliunits ? 'bg-amber-50' : ''}><td className="p-3 font-semibold">{item.name}<span className="ml-2 text-xs font-normal text-slate-400">{item.sku}</span></td><td className="p-3">{displayQuantity(item.onHandMilliunits)} {item.unit}</td><td className="p-3">{displayQuantity(item.reorderLevelMilliunits)} {item.unit}</td><td className="p-3 text-right"><Button size="sm" variant="outline" onClick={() => setAdjustId(item.id)}>Record movement</Button></td></tr>)}</tbody></table></section>
    {adjustId && <form onSubmit={adjust} className="grid gap-3 rounded-2xl border border-indigo-200 bg-indigo-50 p-5 md:grid-cols-4"><div><Label>Movement</Label><select value={movementType} onChange={e => setMovementType(e.target.value)} className="mt-1 h-9 w-full rounded-md border bg-white px-3 text-sm"><option value="receipt">Receipt (+)</option><option value="waste">Waste (-)</option><option value="adjustment">Adjustment (+)</option><option value="count">Count variance (+)</option></select></div><div><Label>Quantity</Label><Input required type="number" min="0.001" step="0.001" value={adjustment} onChange={e => setAdjustment(e.target.value)} /></div><div><Label>Reason</Label><Input required value={reason} onChange={e => setReason(e.target.value)} /></div><div className="flex items-end gap-2"><Button disabled={busy}>Save movement</Button><Button type="button" variant="ghost" onClick={() => setAdjustId(null)}>Cancel</Button></div></form>}
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Menu recipe</h2><p className="mb-4 text-xs text-slate-500">Quantities are deducted when a kitchen item is marked served.</p><select value={recipeMenuId || ''} onChange={e => { setRecipeMenuId(Number(e.target.value)); setRecipeRows([]); }} className="h-9 w-full rounded-md border px-3 text-sm"><option value="" disabled>Select menu item</option>{menuItems.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="mt-3 space-y-2">{recipeRows.map((row, index) => <div key={index} className="flex gap-2"><select value={row.inventoryItemId || ''} onChange={e => setRecipeRows(current => current.map((value, i) => i === index ? { ...value, inventoryItemId: Number(e.target.value) } : value))} className="h-9 flex-1 rounded-md border px-3 text-sm"><option value="" disabled>Ingredient</option>{items.map(item => <option key={item.id} value={item.id}>{item.name} ({item.unit})</option>)}</select><Input className="w-36" type="number" min="0.001" step="0.001" placeholder="Quantity" value={row.quantity} onChange={e => setRecipeRows(current => current.map((value, i) => i === index ? { ...value, quantity: e.target.value } : value))} /><Button type="button" variant="ghost" onClick={() => setRecipeRows(current => current.filter((_, i) => i !== index))}>Remove</Button></div>)}</div><div className="mt-3 flex gap-2"><Button type="button" variant="outline" onClick={() => setRecipeRows(current => [...current, { inventoryItemId: items[0]?.id || 0, quantity: '' }])}><Plus />Ingredient</Button><Button type="button" disabled={busy || !recipeMenuId} onClick={saveRecipe}><Save />Save recipe</Button></div></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="mb-3 font-bold">Recent movements</h2><div className="space-y-2">{movements.slice(0, 20).map(movement => <div key={movement.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-xs"><span>{items.find(item => item.id === movement.inventoryItemId)?.name} · {movement.movementType} · {movement.reason}</span><span className={movement.deltaMilliunits < 0 ? 'text-rose-600' : 'text-emerald-700'}>{movement.deltaMilliunits > 0 ? '+' : ''}{displayQuantity(movement.deltaMilliunits)}</span></div>)}</div></section>
  </div></div>;
}
