import { useEffect, useState } from 'react';
import { LoaderCircle, Printer, RefreshCw, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Profile = { id: number; name: string; jobType: string; connectionType: string };
type Job = { id: number; jobType: string; status: string; attempts: number; lastError: string | null; payload: Record<string, unknown> };

export default function PrintOperationsPanel() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const [name, setName] = useState(''); const [jobType, setJobType] = useState('kitchen'); const [stations, setStations] = useState('main');
  const load = async () => { const [a, b] = await Promise.all([fetch('/api/printers'), fetch('/api/print-jobs')]); if (a.ok) setProfiles(await a.json()); if (b.ok) setJobs(await b.json()); };
  useEffect(() => { void load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { const response = await fetch('/api/printers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, jobType, connectionType: 'browser', stations: stations.split(',').map(value => value.trim()).filter(Boolean) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setName(''); await load(); setMessage('Printer profile created'); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  const test = async (id: number) => { setBusy(true); try { const response = await fetch(`/api/printers/${id}/test`, { method: 'POST' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); setMessage('Test print queued'); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  const processNext = async () => { setBusy(true); setMessage(''); let claimed: Job | null = null; try { const response = await fetch('/api/print-jobs/claim', { method: 'POST' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); claimed = body.job; if (!claimed) { setMessage('No print jobs are ready'); return; } const popup = window.open('', `vc-print-${claimed.id}`, 'width=480,height=720'); if (!popup) throw new Error('Allow pop-ups for this site to use browser printing'); const safe = JSON.stringify(claimed.payload, null, 2).replace(/[&<>]/g, value => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[value]!)); popup.document.write(`<!doctype html><html><head><title>VC POS ${claimed.jobType}</title><style>body{font:14px ui-monospace,monospace;padding:20px;white-space:pre-wrap}h1{font:700 18px system-ui;border-bottom:1px dashed #000;padding-bottom:10px}</style></head><body><h1>VC POS · ${claimed.jobType.toUpperCase()}</h1><pre>${safe}</pre></body></html>`); popup.document.close(); popup.focus(); popup.print(); popup.close(); await fetch(`/api/print-jobs/${claimed.id}/result`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ success: true }) }); setMessage(`Print job ${claimed.id} completed`); } catch (error: any) { if (claimed) await fetch(`/api/print-jobs/${claimed.id}/result`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ success: false, error: error.message }) }).catch(() => undefined); setMessage(error.message); } finally { setBusy(false); await load(); } };
  const retry = async (id: number) => { setBusy(true); try { const response = await fetch(`/api/print-jobs/${id}/retry`, { method: 'POST' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); setMessage('Print job queued for retry'); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  return <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Printer className="size-4 text-indigo-600" /><h2 className="font-bold">Printing & durable queue</h2></div><p className="mt-1 text-xs text-slate-500">Route kitchen/receipt jobs, process browser prints, and retry failures safely.</p></div><div className="flex gap-2"><Button variant="outline" onClick={load}><RefreshCw />Refresh</Button><Button onClick={processNext} disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : <Printer />}Process next job</Button></div></div>{message && <p role="status" className="mt-3 rounded-lg bg-slate-100 p-3 text-xs">{message}</p>}<form onSubmit={create} className="mt-4 grid gap-3 md:grid-cols-4"><div><Label>Printer name</Label><Input required minLength={2} value={name} onChange={event => setName(event.target.value)} /></div><div><Label>Output</Label><select value={jobType} onChange={event => setJobType(event.target.value)} className="mt-1 h-9 w-full rounded-md border px-3 text-sm"><option value="kitchen">Kitchen</option><option value="receipt">Receipt</option></select></div><div><Label>Stations</Label><Input value={stations} onChange={event => setStations(event.target.value)} placeholder="main,grill" /></div><div className="flex items-end"><Button disabled={busy}>Add browser printer</Button></div></form><div className="mt-4 grid gap-2 sm:grid-cols-2">{profiles.map(profile => <div key={profile.id} className="flex items-center justify-between rounded-xl border bg-slate-50 p-3"><div><p className="text-sm font-semibold">{profile.name}</p><p className="text-xs text-slate-500">{profile.jobType} · {profile.connectionType}</p></div><Button size="sm" variant="outline" onClick={() => test(profile.id)}>Test</Button></div>)}</div><div className="mt-5 space-y-2">{jobs.map(job => <div key={job.id} className="flex items-center justify-between gap-3 rounded-xl border p-3 text-xs"><div><p className="font-semibold">#{job.id} · {job.jobType} · {job.status} · attempt {job.attempts}</p>{job.lastError && <p className="mt-1 text-rose-600">{job.lastError}</p>}</div>{['failed', 'dead'].includes(job.status) && <Button size="sm" variant="outline" onClick={() => retry(job.id)}><RotateCcw />Retry</Button>}</div>)}{jobs.length === 0 && <p className="py-4 text-center text-xs text-slate-500">No pending or failed print jobs.</p>}</div></section>;
}
