import { CalendarClock, LoaderCircle, X } from 'lucide-react';
import { useState } from 'react';
import type { RestaurantTable } from '../types.ts';
import { usePos } from '../context/PosContext.tsx';

export default function ReserveTableModal({ table, onClose }: { table: RestaurantTable; onClose: () => void }) {
  const { fetchData, showToast } = usePos(); const soon = new Date(Date.now() + 60 * 60_000); soon.setSeconds(0, 0);
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [at, setAt] = useState(soon.toISOString().slice(0, 16)); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(`/api/tables/${table.id}/reservation`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, phone, reservationAt: new Date(at).toISOString(), notes }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Unable to reserve table'); await fetchData(); showToast(`${table.tableNumber} reserved for ${name}`); onClose(); } catch (cause: any) { setError(cause?.message || 'Unable to reserve table'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-5"><div className="flex items-center gap-2"><CalendarClock className="size-5 text-purple-600" /><div><h2 className="font-bold">Reserve {table.tableNumber}</h2><p className="text-xs text-slate-500">Record who is arriving and when.</p></div></div><button type="button" onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X className="size-4" /></button></header><div className="space-y-3 p-5"><input required minLength={2} maxLength={100} value={name} onChange={e => setName(e.target.value)} placeholder="Guest name" className="w-full rounded-xl border px-3 py-2.5 text-sm" /><div className="grid grid-cols-2 gap-3"><input value={phone} onChange={e => setPhone(e.target.value)} placeholder="Phone (optional)" className="rounded-xl border px-3 py-2.5 text-sm" /><input required type="datetime-local" value={at} min={new Date().toISOString().slice(0, 16)} onChange={e => setAt(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm" /></div><textarea value={notes} maxLength={500} onChange={e => setNotes(e.target.value)} placeholder="Notes (optional)" className="min-h-20 w-full rounded-xl border px-3 py-2.5 text-sm" />{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}<div className="flex gap-2"><button type="button" onClick={onClose} className="flex-1 rounded-xl bg-slate-100 py-2.5 text-xs font-bold">Cancel</button><button disabled={busy || !name.trim()} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-purple-600 py-2.5 text-xs font-bold text-white disabled:opacity-50">{busy && <LoaderCircle className="size-4 animate-spin" />}Save reservation</button></div></div></form></div>;
}
