import { Ban, LoaderCircle, X } from 'lucide-react';
import { useState } from 'react';
import type { OrderItem } from '../types.ts';

export default function VoidOrderItemModal({ item, onClose, onVoid }: { item: OrderItem; onClose: () => void; onVoid: (reason: string) => Promise<void> }) {
  const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (reason.trim().length < 3) return; setBusy(true); try { await onVoid(reason.trim()); onClose(); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/65 p-4 backdrop-blur-sm"><form onSubmit={submit} role="alertdialog" aria-modal="true" aria-labelledby="void-item-title" className="w-full max-w-sm rounded-2xl bg-white text-slate-900 shadow-2xl"><header className="flex items-start justify-between border-b border-rose-100 bg-rose-50 p-5"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-rose-100 text-rose-700"><Ban className="size-5" /></span><div><h2 id="void-item-title" className="font-bold">Void kitchen item</h2><p className="mt-1 text-xs text-rose-700">{item.quantity}× {item.name}</p></div></div><button type="button" onClick={onClose} aria-label="Close" className="rounded-lg p-2 hover:bg-rose-100"><X className="size-4" /></button></header><div className="space-y-4 p-5"><p className="text-xs leading-5 text-slate-600">The item remains in the order history and audit trail. A manager may need to authorize this action.</p><div><label className="mb-1 block text-xs font-bold uppercase tracking-wide text-slate-600">Void reason</label><textarea autoFocus required minLength={3} maxLength={250} value={reason} onChange={event => setReason(event.target.value)} placeholder="For example: customer changed order" className="min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-rose-500" /></div><div className="flex gap-2"><button type="button" onClick={onClose} className="flex-1 rounded-xl bg-slate-100 py-2.5 text-xs font-bold">Keep item</button><button disabled={busy || reason.trim().length < 3} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-rose-600 py-2.5 text-xs font-bold text-white disabled:opacity-50">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Ban className="size-4" />}Void item</button></div></div></form></div>;
}
